# Generated by Django 3.1 on 2022-03-16 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatasourceClone',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('datasource_name', models.CharField(max_length=255, unique=True)),
                ('type', models.TextField(null=True)),
                ('default_ds', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'datasource_clone',
            },
        ),
    ]
